#!/bin/bash 

##########################################################################
#
# Platform: NCI Gadi HPC
# Usage:
# Version: 
#
# For more details see: https://github.com/Sydney-Informatics-Hub/Fastq-to-VCF
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub.
#
# Suggested acknowledgement:
# The authors acknowledge the support provided by the Sydney Informatics Hub,
# a Core Research Facility of the University of Sydney. This research
# was undertaken with the assistance of resources and services from the National
# Computational Infrastructure (NCI), which is supported by the Australian
# Government, and the Australian BioCommons which is enabled by NCRIS via
# Bioplatforms Australia funding.
#
##########################################################################


#PBS -P xh27 
#PBS -N mqc-fq
#PBS -l walltime=01:00:00 
#PBS -l ncpus=1
#PBS -l mem=4GB 
#PBS -q normal 
#PBS -W umask=022 
#PBS -l wd 
#PBS -o ./PBS_logs/multiqc_fastqc.o 
#PBS -e ./PBS_logs/multiqc_fastqc.e 
#PBS -lstorage=scratch/er01+gdata/er01

module load multiqc/1.9   

set -e

out=./MultiQC/FastQC
mkdir -p $out

multiqc -f -d ./FastQC -o ${out}
